# Generated by Django 3.1.6 on 2021-02-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='name',
            field=models.CharField(default='Anime', max_length=500),
        ),
        migrations.AddField(
            model_name='anime',
            name='num_episodes',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
