# Generated by Django 3.1.6 on 2021-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0003_auto_20210210_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='num_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
