# Generated by Django 3.1.6 on 2021-02-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0005_auto_20210210_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='name',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='anime',
            name='premiered',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Airing', 'Currently Airing'), ('Finished Airing', 'Finished Airing')], max_length=256, null=True),
        ),
    ]
