# Generated by Django 3.1.6 on 2021-02-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0008_anime_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='ranked',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
    ]
